FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG NETWORK
ENV NETWORK=${NETWORK}

# Below args are ONLY FOR RAILWAY, don't pass them in docker build command
ARG PRIMARY_RPC_URL
ARG PRIMARY_RPC_ACCESS_TOKEN
ARG FALLBACK_RPC_URL
ARG FALLBACK_RPC_ACCESS_TOKEN

ARG LOG_LEVEL

ARG IPFS_GATEWAY_URL

ARG REDIS_CONNECTION_STRING
ARG POSTGRES_CONNECTION_STRING

ARG VISIBILITY_THRESHOLD_BLOCK_NUMBER

ARG POLLING_INTERVAL
ARG CHUNK_SIZE
ARG CONFIRMATIONS

ARG SKIP_BUILD=false

RUN if [ "$SKIP_BUILD" = "false" ]; then npm run build; fi

CMD ["npm", "start"]
